; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:d1]
platform = espressif32
board = wemos_d1_mini32
framework = arduino
lib_deps = 
	khoih-prog/ESP32TimerInterrupt@^2.3.0
	https://github.com/leandcesar/PeakDetection
upload_port = /dev/tty.usbserial-0264D1KX
monitor_port = /dev/tty.usbserial-0264D1KX
monitor_speed = 115200
-DDEVICE_USED=3
-DDEVICE_MODE=1
platform_packages=
  framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.1
  framework-arduinoespressif32-libs @ https://github.com/espressif/arduino-esp32/releases/download/3.0.1/esp32-arduino-libs-3.0.1.zip

[env:BlinkyV2]
platform = espressif32
board = esp32-s2-saola-1
framework = arduino
lib_deps = 
	khoih-prog/ESP32TimerInterrupt@^2.3.0
	https://github.com/leandcesar/PeakDetection
upload_port = /dev/tty.usbmodem01
monitor_port = /dev/tty.usbmodem01
monitor_speed = 115200
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=0
	-DDEVICE_USED=2
	-DDEVICE_MODE=1

[env:BlinkyV1]
platform = espressif32
board = esp32-s2-saola-1
framework = arduino
lib_deps = 
	khoih-prog/ESP32TimerInterrupt@^2.3.0
	https://github.com/leandcesar/PeakDetection
upload_port = /dev/tty.usbserial-0001
monitor_port = /dev/tty.usbserial-0001
monitor_speed = 115200
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=0
	-DDEVICE_USED=1
	-DDEVICE_MODE=1

[env:BlinkyV3]
platform = espressif32
board = esp32-s2-saola-1
framework = arduino
lib_deps = 
	khoih-prog/ESP32TimerInterrupt@^2.3.0
	https://github.com/leandcesar/PeakDetection
upload_port = /dev/tty.usbmodem01
monitor_port = /dev/tty.usbmodem01
monitor_speed = 115200
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=0
	-DDEVICE_USED=2
	-DDEVICE_MODE=1

