[env]
platform = espressif32
framework = arduino
lib_deps = 
	khoih-prog/ESP32TimerInterrupt@^2.3.0
	#adafruit/RTClib@^2.1.4
    bblanchon/ArduinoJson@^7.0.4
    mathieucarbou/ESP Async WebServer @ ^2.9.4	
build_src_filter = +<../src/> +<../extra_src/>
monitor_speed = 115200


board_build.filesystem = littlefs
[env:main_v2]
board = esp32-s2-saola-1
upload_port = /dev/cu.usbmodem01
monitor_port = /dev/tty.usbmodem01
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=0
	-D DEVICE_USED=2
	-D DEVICE_MODE=0
	-DCORE_DEBUG_LEVEL=5
	-DLOG_LOCAL_LEVEL=ESP_LOG_VERBOSE
	-D CONFIG_ESP_COREDUMP_ENABLE=y
	-D CONFIG_ESP_COREDUMP_UART=y
	-D CONFIG_ESP_COREDUMP_UART_DELAY=0
	-D CONFIG_ESP_COREDUMP_UART_TIMEOUT=1000



[env:Main-V4]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps = 
	khoih-prog/ESP32TimerInterrupt@^2.3.0
    bblanchon/ArduinoJson@^7.0.4
    mathieucarbou/ESP Async WebServer @ ^2.9.4
upload_port = /dev/cu.usbmodem11301
monitor_port = /dev/cu.usbmodem11301
monitor_speed = 115200
upload_speed = 115200
build_type = debug
monitor_filters = esp32_exception_decoder
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1
	-DDEVICE_USED=5
	-DDEVICE_MODE=0
	-DCORE_DEBUG_LEVEL=5
	-DLOG_LOCAL_LEVEL=ESP_LOG_VERBOSE
	-D CONFIG_ESP_COREDUMP_ENABLE=y
	-D CONFIG_ESP_COREDUMP_UART=y
	-D CONFIG_ESP_COREDUMP_UART_DELAY=0
	-D CONFIG_ESP_COREDUMP_UART_TIMEOUT=1000
