; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env]
platform = espressif32
framework = arduino
lib_deps = 
	khoih-prog/ESP32TimerInterrupt@^2.3.0
    bblanchon/ArduinoJson@^7.0.4
    mathieucarbou/ESP Async WebServer @ ^2.9.4	
monitor_speed = 115200
board_build.filesystem = littlefs
platform_packages=
  framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.1
  framework-arduinoespressif32-libs @ https://github.com/espressif/arduino-esp32/releases/download/3.0.1/esp32-arduino-libs-3.0.1.zip


[env:Main-V4]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps = 
	https://github.com/leandcesar/PeakDetection
	bblanchon/ArduinoJson@^7.0.4
upload_port = /dev/cu.usbmodem11201
monitor_port = /dev/cu.usbmodem11201
monitor_speed = 115200
upload_speed = 115200
build_type = debug
debug_tool = esp-prog
monitor_filters = esp32_exception_decoder
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1
	-DDEVICE_USED=5
	-DDEVICE_MODE=0
	-DCORE_DEBUG_LEVEL=5
	-DLOG_LOCAL_LEVEL=ESP_LOG_VERBOSE
	-D CONFIG_ESP_COREDUMP_ENABLE=y
	-D CONFIG_ESP_COREDUMP_UART=y
	-D CONFIG_ESP_COREDUMP_UART_DELAY=0
	-D CONFIG_ESP_COREDUMP_UART_TIMEOUT=1000
build_src_filter = +<../src/> +<../extra_src/>

